In [8]:
import matplotlib.pyplot as plt
import matplotlib
import numpy as np
from numpy import ndarray
%matplotlib inline

from typing import Callable
from typing import Dict

In [17]:
def multiple_inputs_add_backward(x: ndarray,
                                 y: ndarray,
                                 sigma: Array_Function) -> float:
    '''
    Computes the derivative of this simple function with respect to
    both inputs
    '''
    # Compute "forward pass"
    a = x + y

    # Compute derivatives
    dsda = deriv(sigma, a)

    dadx, dady = 1, 1

    return dsda * dadx, dsda * dady

In [18]:
def sigma(x: np.ndarray) -> np.ndarray:
    return 1 / (1 + np.exp(-x))


In [19]:
def deriv(f: Array_Function, x: np.ndarray, h: float = 0.0001) -> np.ndarray:
    return (f(x + h) - f(x - h)) / (2 * h)

In [20]:
Array_Function = Callable[[np.ndarray], np.ndarray]


In [21]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

result = multiple_inputs_add_backward(x, y, sigma)
print(result)

(array([0.00664806, 0.00091022, 0.00012338]), array([0.00664806, 0.00091022, 0.00012338]))


In [22]:
def multiple_inputs_multiply(x: ndarray,
                             y: ndarray,
                             sigma : Array_Function) -> float:
    a = x*y
    dsda = deriv(sigma, a)
    dadx, dady = y,x
    
    return dsda * dadx, dsda*dady

In [23]:
multiple_inputs_multiply(x,y,sigma)

(array([7.06508250e-02, 2.26979036e-04, 9.13802367e-08]),
 array([1.76627062e-02, 9.07916142e-05, 4.56901184e-08]))